### PR TITLE
Update dependencies + rebuild using svd2rust 0.28.0 

### PR DESCRIPTION
**Pull request by jspngh**
- update the dependencies to their latest version.
- increase the MSRV to 1.59 and update the CI accordingly
- rebuild the code with latest svd2rust

### CODE REVIEW

**Comment by jspngh** [comment]
Hmm, not sure why this is failing.

**Comment by 9names** [comment]
Me either - the CI scripts are a bit old and haven't run in a while unfortunately.
Looks like the cargo cache is stale so it can't find the package. I wonder if we can manually update it...

**Comment by 9names** [comment]
Nope. Looks like it will work if you don't try to build for 1.59. something is up with the matrix action.
And we need to remove svdconv for it to work as well since that URL is broken.
Anyway: I've tested with those changes at https://github.com/sipeed/bl602-pac/pull/17 and it's passing.

**Comment by 9names** [comment]
Would you mind if I brought those changes across into this branch?

**Comment by jspngh** [comment]
Go ahead! Do you need permission on my repo for that?

**Comment by 9names** [comment]
Nope, maintainers automatically have permission to edit for PRs - maybe for forks, too.

**Review by 9names — APPROVED** [review]
LGTM

**Pull request merged**
