### PR TITLE
Regenerate Rust code

### PR DESCRIPTION
**Pull request by mkroman**
In this PR I've regenerated the code from the updated SVD file, and I've also created a script to make it easier to regenerate it in the future.

I used svd2rust directly from master, which is at ref [461078befb](https://github.com/rust-embedded/svd2rust/tree/461078befbbdb0ffd0df32cd0d4cb3c4da4de65f) as of writing.

I think we will have to keep using the latest master version for a while to come, since it's already generating a lot of unknown clippy lints and warnings.

### CODE REVIEW

**Comment by 9names** [comment]
PS - Thanks for making a script to automate rebuilding the PAC, it's going to be very handy

**Comment by luojia65** [comment]
LGTM

**Comment by 9names** [comment]
LGTM

**Comment by luojia65** [comment]
Very nice! LGTM

**Pull request merged**
