### PR TITLE
Split UART into UART0 + UART1

### PR DESCRIPTION
**Pull request by jspngh**
I've dusted off my bl602 and am planning to do a project with it.
The main change in this PR is making both UART peripherals available,
but it also updates the dependencies and rebuilds the code with the latest svd2rust.

This will also force some updates to the HAL. I'll create a PR if this gets approved.

### CODE REVIEW

**Comment by 9names** [comment]
Hi! Usually it's best to split these things into separate PRs, so that issues with one PR don't impact the other.
Would you mind updating CI to use a newer version of the compiler as required by the newer svd2rust?

**Comment by 9names** [comment]
MSRV on riscv/riscv-rt is Rust 1.59, this seems like a good version to bump our Minimum Supported Rust Version to.

**Comment by jspngh** [comment]
Alright, will do. I'll create a new PR to:
- update CI
- update dependencies

And then I'll change this PR to only include the UART change.

**Comment by jspngh** [comment]
I'll rebase this once the other PR is merged + do add a commit that regenerates the rust code to reflect the UART updates.

**Comment by jspngh** [comment]
This should be good to merge now.

**Review by 9names — APPROVED** [review]
LGTM

**Pull request merged**
