### PR TITLE
Add reset values and access modifiers from the SDK

### PR DESCRIPTION
**Pull request by username223**
This PR adds reset values and access modifiers directly from the SDK.

The struct fields (specific structs in each commit) parsed looked like
```
Unused		Name                       Width   LSB/MSB      Access       Reset value
V           V                          V         V           V           V
uint32_t field_name                 :  1; /* [   16],        r/w,        0x0 */
```

There are some fields with access values as `w1c` and `w1p`, although I do not know how to represent this in the SVD so they have not been included. In the future those modifiers should also be added.

### CODE REVIEW

**Comment by username223** [comment]
I've rechecked every value and came up with some misapplied reset values and access modifiers, as well as some registers in GLB that I missed because I assumed that I had done them in PR #4.

The `se_trng_0_rosc_en` register is called `se_trng_0_rosc_dis` in the SDK, at the same bit position and in the same register. The name has been changed and a note has been added in the description.

**Comment by username223** [comment]
Fixed merge conflict from PR https://github.com/sipeed/bl602-pac/pull/5.

**Comment by username223** [comment]
Build fails due to warnings 
```
*** WARNING M223: soc602_reg.svd (Line 2) 
  Input File Name 'soc602_reg' does not match the tag <name> in the <device> section: 'BL602'

*** WARNING M209: soc602_reg.svd
  CPU section not set. This is required for CMSIS Headerfile generation and debug support.


Found 0 Error(s) and 2 Warning(s).

Error: Process completed with exit code 1.
```

Until these are fixed the return code of `SVDConv` should be ignored.

**Comment by 9names** [comment]
Ignoring the return code from program using GHA is painful.
I'm going to remove the execution of SVDConv from the workflow for now, and put it in a script or something later so that's easier to test locally

**Comment by username223** [comment]
Couldn't you do something like
```bash
#! /usr/bin/env bash
./SVDConv soc602_reg.svd
if [ $? == 1 ]; then
    exit 0
fi
```

Since return code 0 is nothing, 1 is warning and 2 is error, only capturing 1 will still fail on errors.

**Comment by 9names** [comment]
Yep, that's exactly what we need to do

**Comment by username223** [comment]
Ah, I see what you meant in your original comment now, Github Actions is indeed a little annoying to use at times.

**Comment by username223** [comment]
Corrected duplicated `resetValue`s to `resetMask`s as was originally intended.

**Pull request merged**
